# Generated by Django 4.1.6 on 2023-02-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='link_id',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='link_id',
            field=models.ManyToManyField(to='pars.link'),
        ),
    ]
