# Generated by Django 4.1.6 on 2023-02-03 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pars', '0002_remove_vacancy_link_id_vacancy_link_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='firma_id',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='link_id',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='position_id',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='region_id',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='zarplata_id',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='firma_id',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='pars.firma'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='link_id',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='pars.link'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='position_id',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='pars.position'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='region_id',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='pars.region'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='zarplata_id',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='pars.zarplata'),
        ),
    ]
