# Generated by Django 4.1.6 on 2023-02-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pars', '0003_remove_vacancy_firma_id_remove_vacancy_link_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='zarplata',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
